# Generated by Django 6.0.4 on 2026-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
