# Generated by Django 6.0.4 on 2026-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_component_is_completed_purchaseorder_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#e0e0e0', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='eda_model_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='orders', to='inventory.tag'),
        ),
    ]
