# Generated by Django 6.0.4 on 2026-04-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_tag_component_category_component_eda_model_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='inventory.tag'),
        ),
    ]
